name: Pillow_on_Python_3_9
on: [pull_request, push]
jobs:
  Pillow_on_Python_3_9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install pillow
